# Generated by Django 2.2.7 on 2019-11-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=20, verbose_name='Destination')),
                ('checkin', models.DateField(verbose_name='Check-Out')),
                ('rooms', models.IntegerField(verbose_name='Rooms')),
            ],
        ),
    ]
