# Generated by Django 2.2.7 on 2019-11-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='checkout',
            field=models.DateField(auto_now=True, verbose_name='Check-Out'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='checkin',
            field=models.DateField(auto_now=True, verbose_name='Check-In'),
        ),
    ]
